name: "Hello world"
description: "Actions manifest, created to reply a greeting and save the date"
inputs:
  who-to-greet: # id of input
  description: 'Who to greet'
  required: true
  default: 'World'
outputs:
  time: # id of output
  description: "The date we met"
runs:
  using: 'docker'
  image: 'Dockerfile'
  args: 
    - ${{ inputs.who-to-greet }}